const {
  MONGO_URI,
  PORT,
  DEBUG_MODE,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  EMAIL,
  PASSWORD,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
} = process.env;

module.exports = {
  MONGO_URI,
  PORT,
  DEBUG_MODE,
  ACCESS_TOKEN,
  REFRESH_TOKEN,
  EMAIL,
  PASSWORD,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
};
